### ISSUE TITLE
Copy Elision 

### ISSUE THREAD

**Issue by mik30s** [wmww/glx_test#1]
I was browsing through and I found some parts of the code that could use copy elision
https://github.com/william01110111/glx_test/blob/master/ShaderProgram.cpp#L20
https://github.com/william01110111/glx_test/blob/master/ShaderProgram.cpp#L51

I did not create a PR because i felt it may not be welcome.

**Comment by wmww** [comment]
Since they are in error reporting functions that generally aren't called, the slight performance boost is negligible.
